### ISSUE TITLE
Not working with D* 0.6.x

### ISSUE THREAD

**Issue by Pafzedog** [noplanman/DiasPlus#9]
Hello,

you script seems to be awesome but unfortunately it's not working with new D* version.
Do you think you will update it to work ?

**Comment by noplanman** [comment]
Uff, I've semi-abandoned this project cause I thought nobody was really using it, but I will see to release an updated version for 0.6, which is way overdue.

Thanks for letting me know that it's used by at least 1 person 😄

**Comment by Pafzedog** [comment]
haha :D 
hum ... I think lots of people will be interested in your script because I saw many demands of nearly similar features, community of Diaspora is growing fast actually .
- Crosspod link feature should be very useful to share a post from another pod
- adding "hide tag/user" should be cool too.

btw thx for your answer :)

**Comment by noplanman** [comment]
I just need to stop being lazy and get coding again 😄 

As soon as I have a working version for 0.6, feel free to share it so that more people know about it.

**Comment by Pafzedog** [comment]
You can be sure I will flood my pod :)

**Comment by noplanman** [comment]
@Pafzedog Please give 2.0.0 a try and let me know if all is good 😊 

Now, only 0.6+ is supported!

**Comment by Pafzedog** [comment]
oh yeah ! I'll try this evening :)

**Comment by Pafzedog** [comment]
Awesome !
very good work :)
all features are working except "reverse message order", I can't see the button :
![buttons](http://pix.toile-libre.org/upload/original/1479933965.png)

**Comment by noplanman** [comment]
The button should be next to the big "X" on the top right when you're in a conversation.
It doesn't work for posts, just messages in a conversation.

**Comment by Pafzedog** [comment]
haaa... ok sorry for that, I did not understand this one ;)
